page_contacts:
    pattern:  /contacts
    defaults: { _controller: GeekhubResourceBundle:Page:contacts }

faq:
    pattern:  /faq/{slug}
    defaults: { _controller: "GeekhubResourceBundle:Faq:faqList", slug: null }

page_about:
    pattern:  /about
    defaults: { _controller: "GeekhubResourceBundle:Page:about" }
