page_contacts:
    pattern:  /contacts
    defaults: { _controller: GeekhubResourceBundle:Page:contacts }

faq:
    pattern:  /faq/{slug}
    defaults: { _controller: "GeekhubResourceBundle:Faq:index", slug: null }
