page_contacts:
    pattern:  /contacts
    defaults: { _controller: GeekhubResourceBundle:Page:contacts }

faq:
    pattern:  /faq/{slug}
    defaults: { _controller: "GeekhubResourceBundle:Faq:index", slug: null }

faq_show:
    pattern:  /faq/{slug}/show
    defaults: { _controller: "GeekhubResourceBundle:Faq:show" }
