page_contacts:
    pattern:  /contacts
    defaults: { _controller: GeekhubResourceBundle:Page:contacts }

faq:
    pattern:  /faq/{slug}
    defaults: { _controller: "GeekhubResourceBundle:Faq:faqList", slug: null }

faqs:
    type: rest
    resource: Geekhub\ResourceBundle\Controller\FaqController
