_imagine:
    resource: .
    type:     imagine

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

media_internal_api:
    resource: '@ApplicationSonataMediaBundle/Resources/config/api.yml'
    prefix: /internal-api/media
