NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /

dream:
    type: rest
    resource: "@GeekhubDreamBundle/Controller/Api/DreamController.php"

faq:
    type: rest
    resource: "@GeekhubResourceBundle/Controller/Api/FaqController.php"
