NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

dream:
    type: rest
    resource: "@GeekhubDreamBundle/Controller/Api/DreamController.php"
