_imagine:
    resource: .
    type:     imagine

_domain_routing:
    resource: .
    type: domain_routing

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
