_imagine:
    resource: .
    type:     imagine

geekhub_dream:
    resource: "@GeekhubDreamBundle/Resources/config/routing.yml"
    prefix:   /

geekhub_tag:
    resource: "@TagBundle/Resources/config/routing.yml"
    prefix:   /tags

geekhub_user:
    resource: "@GeekhubUserBundle/Resources/config/routing.yml"
    prefix:   /

geekhub_resource:
    resource: "@GeekhubResourceBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

media_internal_api:
    resource: '@ApplicationSonataMediaBundle/Resources/config/api.yml'
    prefix: /internal-api/media

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
