# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

     user_class_name: Geekhub\UserBundle\Entity\User

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     aouth_user_provider:
         class: Geekhub\UserBundle\Model\OAuthUserProvider
         arguments:
            - @doctrine
            - %user_class_name%
