services:
    monitor.check.php_extensions:
        class: Geekhub\DreamBundle\Check\TravisCheck
        arguments:
            - "geekhub-php"
            - "CheDream"
            - "AddPermisionForDashboard"
        tags:
            - { name: liip_monitor.check, alias: monitor_travis }