hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"

profile_update_contacts:
    pattern: /user/updateContacts
    defaults: { _controller: GeekhubUserBundle:User:updateContacts }

merge_accounts:
    pattern: /merge-accounts/{user}
    defaults: { _controller: GeekhubUserBundle:User:mergeAccounts }
