Geekhub\DreamBundle\Entity\Dream:
    exclusion_policy: ALL
    properties:
        Id:
            expose: true
            type: integer
        title:
            expose: true
            type: string
        slug:
            expose: true
            type: string
        description:
            expose: true
            type: string
