Geekhub\DreamBundle\Entity\Dream:
    exclusion_policy: ALL
    properties:
        Id:
            expose: true
            type: integer
        title:
            expose: true
            type: string
        slug:
            expose: true
            type: string
        description:
            expose: true
            type: string
        phone:
           expose: true
           type: integer
        createdAt:
           expose: true
           type: DateTime
        updatedAt:
           expose: true
           type: DateTime
        deletedAt:
           expose: true
        financialCompleted:
           expose: true
        workCompleted:
           expose: true
        equipmentCompleted:
           expose: true
        currentStatus:
           expose: true
