Geekhub\DreamBundle\Entity\AbstractContributeResource:
    exclusion_policy: ALL
    properties:
        createdAt:
           expose: true
           type: DateTime
        quantity:
           expose: true
           type: integer
        dream:
           expose: true
           type: array<Geekhub\DreamBundle\Entity\Dream>

