<?php

namespace Geekhub\DreamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DreamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DreamRepository extends EntityRepository
{
    public function  getDreamsByStatus($status)
    {

        return $this->getEntityManager()->getRepository('GeekhubDreamBundle:Dream')->findBy(array(
            'currentStatus' => $status
        ));
    }
}
