<?php

namespace Geekhub\DreamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DreamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DreamRepository extends EntityRepository
{
}
