<?php

namespace Geekhub\DreamBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Dreams_needingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DreamNeedingRepository extends EntityRepository
{
}
