geekhub_dream_homepage:
    pattern:  /
    defaults: { _controller: GeekhubDreamBundle:Default:index }

new_dream:
    pattern:  /dream/new
    defaults: { _controller: GeekhubDreamBundle:Dream:newDream }
    options:
        expose: true

dream_list:
    pattern:  /dream/list
    defaults: { _controller: GeekhubDreamBundle:Dream:listAllDream }
    options:
        expose: true

dream_change_status:
    pattern:  /dream/chst
    defaults: { _controller: GeekhubDreamBundle:Dream:changeStatus }

dream_ajax_load_image:
    pattern:  /dream/ajaxLoadImage
    defaults: { _controller: GeekhubDreamBundle:AjaxDream:DreamImageLoader }
    options:
        expose: true

dream_ajax_load_poster:
    pattern:  /dream/ajaxLoadPoster
    defaults: { _controller: GeekhubDreamBundle:AjaxDream:DreamPosterLoader }
    options:
        expose: true

dream_media_info:
    pattern:  /dream/media/{id}
    defaults: { _controller: GeekhubDreamBundle:Dream:MediaInfo }
