Geekhub\UserBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
#        firstName:
#            expose: true
#            type: string
#        middleName:
#            expose: true
#            type: string
#        lastName:
#            expose: true
#            type: string
#        avatar:
#            expose: true