geekhub_dream_homepage:
    pattern:  /
    defaults: { _controller: GeekhubDreamBundle:HomePage:home }

new_dream:
    pattern:  /dream/new
    defaults: { _controller: GeekhubDreamBundle:Dream:newDream }
    options:
        expose: true

edit_dream:
    pattern:  /dream/edit/{slug}
    defaults: { _controller: GeekhubDreamBundle:Dream:editDream }

view_dream:
    pattern:  /dreams/{slug}
    defaults: { _controller: GeekhubDreamBundle:Dream:viewDream }

reject_dream:
    pattern:  /dream/reject/{slug}
    defaults: { _controller: GeekhubDreamBundle:Dream:rejectDream }

confirm_dream:
    pattern:  /dream/confirm/{slug}
    defaults: { _controller: GeekhubDreamBundle:Dream:confirmDream }

implementing_dream:
    pattern:  /dream/implementing/{slug}
    defaults: { _controller: GeekhubDreamBundle:Dream:implementingDream }

implementing_dream_edit_yellowBlock:
    pattern:  /dream/editingyellowblock/{slug}
    defaults: { _controller: GeekhubDreamBundle:Dream:editInformationDream }

completed_dream:
    pattern:  /dream/completing/{slug}
    defaults: { _controller: GeekhubDreamBundle:Dream:completingDream }

successed_dream:
    pattern:  /dream/successed/{slug}
    defaults: { _controller: GeekhubDreamBundle:Dream:successDream }

failed_dream:
    pattern:  /dream/failed/{slug}
    defaults: { _controller: GeekhubDreamBundle:Dream:failDream }

dream_by_tag:
    pattern:  /dream/tag/{tag}
    defaults: { _controller: GeekhubDreamBundle:Dream:dreamsByTag }

dream_list:
    pattern:  /dreams
    defaults: { _controller: GeekhubDreamBundle:Dream:list }

dream_search:
    pattern:  /dream/searchForm
    defaults: { _controller: GeekhubDreamBundle:Dream:search }

dream_search_text:
    pattern:  /dream/search/{text}
    defaults: { _controller: GeekhubDreamBundle:Dream:searchDream }

dream_ajax_load_image:
    pattern:  /dream/ajaxLoadImage
    defaults: { _controller: GeekhubDreamBundle:AjaxDream:dreamImageLoader }
    options:
        expose: true

dream_ajax_load_completed_image:
    pattern:  /dream/ajaxLoadCompletedImage
    defaults: { _controller: GeekhubDreamBundle:AjaxDream:dreamCompletedPicturesLoader }
    options:
        expose: true

dream_ajax_load_poster:
    pattern:  /dream/ajaxLoadPoster
    defaults: { _controller: GeekhubDreamBundle:AjaxDream:dreamPosterLoader }
    options:
        expose: true

dream_ajax_remove_media:
    pattern:  /dream/ajaxRemovePicture
    defaults: { _controller: GeekhubDreamBundle:AjaxDream:dreamPictureRemove }
    options:
        expose: true

dream_ajax_dream_toFavorite:
    pattern:  /dream/ajaxAddDreamToFavorite
    defaults: { _controller: GeekhubDreamBundle:AjaxDream:addDreamToFavorite }
    options:
        expose: true
